package com.felipeporceli.application.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;


@Entity
@Table(name = "tb_category")
public class Category implements Serializable {
    private static final long serialVersionUID = 1L;

    /* PT-BR: Campo id é a chave primária, gerada automaticamente pelo banco.
       EN-US: id field is the primary key, automatically generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    private String name;
    @JsonIgnore
    @ManyToMany(mappedBy = "categories")
    /*PT-BR: Relacionamento muitos-para-muitos com Product.
            "mappedBy" indica que o lado dono da relação está em Product (atributo "categories").
            @JsonIgnore evita loop infinito no JSON (Category -> Products -> Category -> ...).
     EN-US: Many-to-many relationship with Product.
            "mappedBy" indicates that the owning side is in Product (field "categories").
            @JsonIgnore prevents infinite JSON recursion
            (Category -> Products -> Category -> ...). */
    private Set<Product> products = new HashSet<>();
    public Category () {}

    public Category(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Set<Product> getProducts() {
        return products;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        return Objects.equals(id, category.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}

