package com.felipeporceli.application.entities;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;

@Entity
@Table(name = "tb_payment")
public class Payment implements Serializable {
    private static final Long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    /* PT-BR: Chave primária gerada automaticamente pelo banco de dados
       EN-US: Primary key automatically generated by the database */
    private Integer id;

    @JsonFormat(shape = JsonFormat.Shape.STRING,
            pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'",
            timezone = "GMT")
    /* PT-BR: Formatação da data ao serializar para JSON (padrão ISO 8601 em UTC)
       EN-US: Date formatting when serializing to JSON (ISO 8601 format in UTC) */
    private Instant moment;

    @OneToOne
    @MapsId
    @JsonIgnore
    /* PT-BR: Relacionamento 1:1 com Order.
              @MapsId indica que o Payment usará o mesmo ID do Order como chave primária.
              @JsonIgnore evita loop infinito ao converter para JSON.
       EN-US:  One-to-one relationship with Order.
              @MapsId indicates that Payment shares the same ID as Order as primary key.
              @JsonIgnore prevents infinite recursion when converting to JSON. */
    private Order order;

    public Payment() {
    }

    public Payment(Integer id, Instant moment, Order order) {
        this.id = id;
        this.moment = moment;
        this.order = order;
    }

    /* PT-BR: Retorna o ID do pagamento
       EN-US: Returns the payment ID */
    public Integer getId() {
        return id;
    }

    /* PT-BR: Define o ID do pagamento
       EN-US: Sets the payment ID */
    public void setId(Integer id) {
        this.id = id;
    }

    /* PT-BR: Retorna o momento em que o pagamento foi confirmado
       EN-US: Returns the timestamp when the payment was confirmed */
    public Instant getMoment() {
        return moment;
    }

    /* PT-BR: Define o momento do pagamento
       EN-US: Sets the payment timestamp */
    public void setMoment(Instant moment) {
        this.moment = moment;
    }

    /* PT-BR: Retorna o pedido associado ao pagamento
       EN-US: Returns the order associated with the payment */
    public Order getOrder() {
        return order;
    }

    /* PT-BR: Relaciona um pagamento ao seu pedido
       EN-US: Associates a payment to its order */
    public void setOrder(Order order) {
        this.order = order;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Payment payment = (Payment) o;
        return Objects.equals(id, payment.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}

